# Generated by Django 2.2.6 on 2019-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sale ID')),
                ('dop', models.DateField(verbose_name='Date of Purchase')),
                ('customer_id', models.BigIntegerField()),
                ('fuel', models.CharField(choices=[('CNG', 'CNG'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=10)),
                ('vehicle_segment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('selling_price', models.FloatField()),
                ('power_steering', models.BooleanField()),
                ('airbags', models.BooleanField()),
                ('sunroof', models.BooleanField()),
                ('matt_finish', models.BooleanField()),
                ('music_system', models.BooleanField()),
                ('customer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('customer_income_group', models.CharField(choices=[('0- $25K', '0- $25K'), ('$25-$70K', '$25-$70K'), ('>$70K', '>$70K')], max_length=10)),
                ('customer_region', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=10)),
                ('customer_marital_status', models.BooleanField()),
            ],
        ),
    ]
