# Generated by Django 2.2.6 on 2019-10-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_marital_status',
            field=models.CharField(choices=[(1, 'Married'), (0, 'Unmarried')], max_length=1),
        ),
    ]
