# Generated by Django 2.2.6 on 2019-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_auto_20191009_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.FloatField(max_length=10),
        ),
    ]
