# Generated by Django 2.2.6 on 2019-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_auto_20191011_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.FloatField(),
        ),
    ]
