# Generated by Django 2.2.6 on 2019-10-11 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_auto_20191011_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.FloatField(verbose_name=django.core.validators.MaxValueValidator(100000)),
        ),
    ]
