# Generated by Django 2.2.6 on 2019-10-11 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_auto_20191011_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
